### ISSUE TITLE
Get attributes of cluster by clusterId and profileId

### ISSUE THREAD

**Issue by auschmann** [zigbeer/zcl-id#3]
Hi,

i think it would be very helpful to be able to get
the list of attributes an cluster has.

something like:
```javascript
zclId.attributes('genBasic', 4); // [{ attrId: 3, dataType: 32}, ... ]
```

As i missing something or is this out of scope of zcl-id?

**Comment by simenkid** [comment]
Hi @auschmann. I can add an API for exporting them, that's ok for me. I was just wondering when do you need to know all the attributes at once from this dictionary? 

Some attributes are optional, attributes that a device actually uses may not include all of them.

**Comment by auschmann** [comment]
Hi,

thanks for the quick response. Good to see that this project is still activeley maintained.

we are currently working on a project to build a zigbee coordinator which connects to our cloud service. Our cloud service will then expose an easy REST-API which provides endpoints for several zigbee related tasks. 

For example, our cloud service provides an API to get the list of EndDevices that are connected to the zigbee network. For each EndDevice that is reported we would like to include the simpleDedcriptor and all clusters including the attribute types and names.

For this reason it would be really helpful to be able to loop over cluster IDs and build the response with the help of zcl-id.

You are correct:
It would he even better if zcl-id would also report if an attribute is optional and if it's readable/writeable.

I hope this makes sense.

**Comment by simenkid** [comment]
Hello @auschmann. That's nice to have ZigBee network be part of the web world. I think you don't have to get a whole list of attributes, instead using `attr(cId, attrId)` and `attrType(cId, attrId)` APIs would be enough.

Assume that a cluster **may** has three - `A`, `B`, `C` - attributes, where `C` is optional. If `C` is not implemented by the manufacturer, then you will only get `A` and `B` when discovering attributes in a cluster from the remote device. Thus it seems no need to have a whole list defined by the ZCL spec at very beginning.

Have you heard of the **[zigbee-shepherd](https://github.com/zigbeer/zigbee-shepherd)**? Which is a project that extends a coordinator to a gateway. In addition, it's also a zigbee application framework that allows users to implement the standard ZApp with node.js. WIth the framework, you can `list()` all devices joined, `find()` a certain endpoint, `getSimpleDesc()`  and `dump()` the information about an endpoint. Something like:

```js
{
    profId: 260,
    epId: 8,
    devId: 0,
    inClusterList: [ 0, 3 ],
    outClusterList: [ 3, 6 ],
    clusters: {
        genBasic: {
            dir: { value: 1 },    // in Cluster
            attrs: {
                 hwVersion: 0,
                 manufacturerName: 'TexasInstruments',
                 modelId: 'TI0001          ',
                 dateCode: '20060831        ',
                 powerSource: 1,
                 locationDesc: '                ',
                 physicalEnv: 0,
                 deviceEnabled: 1
             }
         },
         genIdentify: {
             dir: { value: 3 },    // in and out Cluster
             attrs: {
                 identifyTime: 0
             }
         },
         genOnOff:{
             dir: { value: 2 },    // out Cluster
             attrs: {
                 onOff: 0
             }
         }
     }
 }
```

With the help of **zigbee-shepherd**, then creating REST APIs may be just a piece of cake. It's very easy to be integrated with node.js servers (in-program). And you can also use socket.io or generic websockets to create a real-time message channel for receiving indications from remote devices (instead of polling them by REST APIs).

Anyway, if you do like have a list of the defined attributes, I'm ok with it. Or maybe a json file would be enough?

**Comment by auschmann** [comment]
Hey @simenkid,

thanks for the explanation this really helped me a lot.
In fact we are currently evaluating our options when it comes to implementation.
We already played around with zigbee-shepherd and we were quite impressed from the beginning.

Anyway we decided to use the zigbee linux gateway which is provides an abstraction on top of z-stack for our coordinator. Nevertheless zcl-id will come in handy in our project. We decided to build our coordinator using z-stack because shepherd and even zcl-id did sometimes crash unexpectetly which makes it hard for our application to recover from this errors.

When i find the time i will open an issue describing the error in the respective repositories.

Anyway i have much respect for the effort that you put in shepherd until now and i hope that it will involve even more as it has the chance to become the framework of choice when it´s ready for production.

May i ask you in which environment you are building shepherd?
Do you do it as a side project or is it the ground work for a paid product development?

Kind regards

André

**Comment by simenkid** [comment]
Hi @auschmann ,

  I just bump zcl-id to v0.3.0, there is a new method [.attrList()](https://github.com/zigbeer/zcl-id/wiki#API_attrList) for your convenience. 

  Actually, **zigbee-shepherd** is the ground work for another open source project which integrates [BLE](https://github.com/bluetoother/ble-shepherd), [ZigBee](https://github.com/zigbeer/zigbee-shepherd), [CoAP](https://github.com/PeterEB/coap-shepherd), and [MQTT](https://github.com/lwmqn/mqtt-shepherd) into a multi- and cross-protocol machine network. (As you can see, they are 4 shepherds, and can run independently)

  We build our shepherds with Ubuntu, and have deployed them to PC, Raspberry Pi, and Beaglebone Wireless Green. Back to the zigee-shepherd, I'm not sure which version you were with? Since the older versions are very unstable. We are currently in the stage of testing, and trying to make it more stable. So far, in our environment, zigbee-shepherd works fine with many commercial products. We will try our best to roll out the first stable release as soon as possible. We hope for your feedback if you find anything goes wrong. 😄

**Comment by simenkid** [comment]
Hello @auschmann . I hope the newer bump meets your needs. May we close this issue? If you like to exchange some thoughts, we can keep posting within this closed issue.
